version: 2

sources:
  - name: raw
    database: gz_raw_data
    schema: raw

    tables:
      - name: sales
        identifier: raw_gz_sales
        columns:
          - name: date_date
          - name: orders_id
          - name: pdt_id
          - name: revenue
          - name: quantity

      - name: product
        identifier: raw_gz_product
        columns:
          - name: products_id
          - name: purchSE_PRICE

      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
          - name: shipping_fee
          - name: shipping_fee_1
          - name: log_Cost
          - name: ship_cost
          